version: '3.4'

services: 
    financeapp:
        build: .
        command: bash -c "python manage.py initadmin 1 --admin && python manage.py runserver 0.0.0.0:8000"
        volumes: 
            - .:/app
        ports: 
            - 8024:8000