version: '3.4'

services:
    financeapp:
        restart: always
        build: .
        command: bash -c "python manage.py runserver 0.0.0.0:8000"
        volumes: 
            - .:/app
        ports: 
            - 8024:8000
