# Generated by Django 3.0.8 on 2020-07-22 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(max_length=50)),
                ('currency_symbol', models.CharField(max_length=50)),
                ('currency_name', models.CharField(max_length=50)),
                ('currency_id', models.CharField(max_length=50, unique=True)),
            ],
        ),
    ]
