# Generated by Django 3.0.8 on 2020-07-22 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency_converter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='currency_id',
            field=models.CharField(max_length=50),
        ),
    ]
